services:
  ldap:
    image: bitnami/openldap
    environment:
      LDAP_ORGANISATION: ExampleOrg
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CUSTOM_SCHEMA_DIR: /_data/schemas
      LDAP_USERS: demo,user1
      LDAP_PASSWORDS: demo,user1
      LDAP_GROUP: test
    volumes:
      - './data/ldap-schemas:/_data/schemas'
    ports:
      - "389:1389"

  phpldapadmin:
    # Configuration:
    # - Login: cn=admin,dc=example,dc=org
    # - Password: admin
    #

    image: phpldapadmin/phpldapadmin:2.1.4
    container_name: phpldapadmin
    environment:
      LDAP_HOST: ldap
      LDAP_PORT: '1389'
      LDAP_BASE_DN: dc=example,dc=org
      LDAP_USERNAME: cn=admin,dc=example,dc=org
      LDAP_PASSWORD: admin
      LDAP_LOGIN_ATTR: cn
      LDAP_ALLOW_GUEST: 'TRUE'
    ports:
      - "8084:8080"
    depends_on:
      - ldap

  keycloak:
    # Keycloak configuration:
    # 1. Navigate to "User federation -> ldap"
    # 2. Configure:
    #   - Vendor: other
    #   - Connection URL: ldap://ldap:389
    #   - Bind DN: cn=admin,dc=example,dc=org
    #   - Bind Credential: admin
    #   - Users DN: dc=example,dc=org
    # 3. Select "Test connection"
    # 4. Select "Test authentication"
    #

    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - 8085:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

