services:
  ldap:
    image: bitnami/openldap
    environment:
      LDAP_ORGANISATION: ExampleOrg
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CUSTOM_SCHEMA_DIR: /_data/schemas
      LDAP_USERS: demo,user1
      LDAP_PASSWORDS: demo,user1
      LDAP_GROUP: test
    volumes:
      - './data/ldap-schemas:/_data/schemas'
    ports:
      - "389:1389"

  phpldapadmin:
    # Configuration:
    # - Login: cn=admin,dc=example,dc=org
    # - Password: admin
    #

    image: phpldapadmin/phpldapadmin:2.1.4
    container_name: phpldapadmin
    environment:
      LDAP_HOST: ldap
      LDAP_PORT: '1389'
      LDAP_BASE_DN: dc=example,dc=org
      LDAP_USERNAME: cn=admin,dc=example,dc=org
      LDAP_PASSWORD: admin
      LDAP_LOGIN_ATTR: cn
      LDAP_ALLOW_GUEST: 'TRUE'
    ports:
      - "8084:8080"
    depends_on:
      - ldap

