services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: ExampleOrg
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "389:389"

  phpldapadmin:
    # Configuration:
    # - Login: cn=admin,dc=example,dc=org
    # - Password: admin
    #

    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap

  keycloak:
    # Keycloak configuration:
    # 1. Navigate to "User federation -> ldap"
    # 2. Configure:
    #   - Vendor: other
    #   - Connection URL: ldap://ldap:389
    #   - Bind DN: cn=admin,dc=example,dc=org
    #   - Bind Credential: admin
    #   - Users DN: dc=example,dc=org
    # 3. Select "Test connection"
    # 4. Select "Test authentication"
    #

    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - 8085:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

