{
 "title": "MDB Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Read - Endpoint Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(mdb_get_movie_calls[1m])",
     "legendFormat": "Get Movie"
    },
    {
     "expr": "increase(mdb_get_movie_collection_calls[1m])",
     "legendFormat": "Get Movie Collection"
    },
    {
     "expr": "increase(mdb_search_movies_calls[1m])",
     "legendFormat": "Search Movies"
    },
    {
     "expr": "increase(mdb_search_movie_collections_calls[1m])",
     "legendFormat": "Search Movie Collections"
    }
   ]
  },
  {
   "title": "Write - Endpoint Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(mdb_create_movie_calls[1m])",
     "legendFormat": "Create Movie"
    },
    {
     "expr": "increase(mdb_create_movie_collection_calls[1m])",
     "legendFormat": "Create Movie Collection"
    }
   ]
  },
  {
   "title": "Relevant Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"mdb\", level!=\"debug\"}"
    }
   ]
  },
  {
   "title": "Debug Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"mdb\", level=\"debug\"}"
    }
   ]
  }
 ]
}